variable "caller" {}

variable "envname" {
    default = []
}

variable "fqdn" {
    default = []
}

variable "certificate" {}

variable "description" {}

variable "svc" {
    default = "Generated by Terraform"
}

locals {
    scale = 1
    enabled = "${contains(var.envname,"${var.caller}")==true ? 1 : 0}"
    farm = "${local.scale * local.enabled}"
}
