variable "caller" {}

variable "envname" {
    default = []
}

variable "name" {}

variable "description" {}

variable "svc" {
    default = "Generated by Terraform"
}

variable "usage" {
    default = "ENCRYPT_DECRYPT"
}

variable "policy" {
    default = ""
}

variable "delete_time" {
    default = 30
}

variable "enabled" {
    default = "true"
}

variable "rotate" {
    default = "false"
}

locals {
    scale = 1
    enabled = "${contains(var.envname,"${var.caller}")==true ? 1 : 0}"
    farm = "${local.scale * local.enabled}"
}
