variable "caller" {}

variable "aws_service" {}

variable "suffix" {
    default = null
}

variable "description" {
    default = "Generated by Terraform"
}

locals {
    scale = 1
    enabled = "${contains(var.envname,"${var.caller}")==true ? 1 : 0}"
    farm = "${local.scale * local.enabled}"
}
